CREATE TABLE `ps_map_data_halflife_bg3` (
  `dataid` int unsigned NOT NULL default '0',
  `britishkills` smallint unsigned NOT NULL default '0',
  `americanskills` smallint unsigned NOT NULL default '0',
  `joinedbritish` smallint unsigned NOT NULL default '0',
  `joinedamericans` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `britishwon` smallint unsigned NOT NULL default '0',
  `britishlost` smallint unsigned NOT NULL default '0',
  `americanswon` smallint unsigned NOT NULL default '0',
  `americanslost` smallint unsigned NOT NULL default '0',
  `britishflagscaptured` smallint unsigned NOT NULL default '0',
  `americansflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ps_plr_data_halflife_bg3` (
  `dataid` int unsigned NOT NULL default '0',
  `britishkills` smallint unsigned NOT NULL default '0',
  `americanskills` smallint unsigned NOT NULL default '0',
  `britishdeaths` smallint unsigned NOT NULL default '0',
  `americansdeaths` smallint unsigned NOT NULL default '0',
  `joinedbritish` smallint unsigned NOT NULL default '0',
  `joinedamericans` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `britishwon` smallint unsigned NOT NULL default '0',
  `britishlost` smallint unsigned NOT NULL default '0',
  `americanswon` smallint unsigned NOT NULL default '0',
  `americanslost` smallint unsigned NOT NULL default '0',
  `britishflagscaptured` smallint unsigned NOT NULL default '0',
  `americansflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ps_plr_maps_halflife_bg3` (
  `dataid` int unsigned NOT NULL default '0',
  `britishkills` smallint unsigned NOT NULL default '0',
  `americanskills` smallint unsigned NOT NULL default '0',
  `britishdeaths` smallint unsigned NOT NULL default '0',
  `americansdeaths` smallint unsigned NOT NULL default '0',
  `joinedbritish` smallint unsigned NOT NULL default '0',
  `joinedamericans` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `britishwon` smallint unsigned NOT NULL default '0',
  `britishlost` smallint unsigned NOT NULL default '0',
  `americanswon` smallint unsigned NOT NULL default '0',
  `americanslost` smallint unsigned NOT NULL default '0',
  `britishflagscaptured` smallint unsigned NOT NULL default '0',
  `americansflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
