CREATE TABLE `ps_map_data_halflife_dod` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ps_plr_data_halflife_dod` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `alliesdeaths` smallint unsigned NOT NULL default '0',
  `axisdeaths` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ps_plr_maps_halflife_dod` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `alliesdeaths` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `axisdeaths` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
