CREATE TABLE `ps_map_data_halflife_dod` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `allieskills` smallint(5) unsigned NOT NULL default '0',
  `axiskills` smallint(5) unsigned NOT NULL default '0',
  `joinedallies` smallint(5) unsigned NOT NULL default '0',
  `joinedaxis` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `allieswon` smallint(5) unsigned NOT NULL default '0',
  `allieslost` smallint(5) unsigned NOT NULL default '0',
  `axiswon` smallint(5) unsigned NOT NULL default '0',
  `axislost` smallint(5) unsigned NOT NULL default '0',
  `bombplanted` smallint(5) unsigned NOT NULL default '0',
  `bombdefused` smallint(5) unsigned NOT NULL default '0',
  `killedbombplanter` smallint(5) unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `axisflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `flagscaptured` smallint(5) unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint(5) unsigned NOT NULL default '0',
  `axisflagsblocked` smallint(5) unsigned NOT NULL default '0',
  `flagsblocked` smallint(5) unsigned NOT NULL default '0',
  `alliesscore` smallint(5) unsigned NOT NULL default '0',
  `axisscore` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_data_halflife_dod` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `allieskills` smallint(5) unsigned NOT NULL default '0',
  `axiskills` smallint(5) unsigned NOT NULL default '0',
  `alliesdeaths` smallint(5) unsigned NOT NULL default '0',
  `axisdeaths` smallint(5) unsigned NOT NULL default '0',
  `joinedallies` smallint(5) unsigned NOT NULL default '0',
  `joinedaxis` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `allieswon` smallint(5) unsigned NOT NULL default '0',
  `allieslost` smallint(5) unsigned NOT NULL default '0',
  `axiswon` smallint(5) unsigned NOT NULL default '0',
  `axislost` smallint(5) unsigned NOT NULL default '0',
  `bombplanted` smallint(5) unsigned NOT NULL default '0',
  `bombdefused` smallint(5) unsigned NOT NULL default '0',
  `killedbombplanter` smallint(5) unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `axisflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `flagscaptured` smallint(5) unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint(5) unsigned NOT NULL default '0',
  `axisflagsblocked` smallint(5) unsigned NOT NULL default '0',
  `flagsblocked` smallint(5) unsigned NOT NULL default '0',
  `alliesscore` smallint(5) unsigned NOT NULL default '0',
  `axisscore` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_maps_halflife_dod` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `allieskills` smallint(5) unsigned NOT NULL default '0',
  `alliesdeaths` smallint(5) unsigned NOT NULL default '0',
  `axiskills` smallint(5) unsigned NOT NULL default '0',
  `axisdeaths` smallint(5) unsigned NOT NULL default '0',
  `joinedallies` smallint(5) unsigned NOT NULL default '0',
  `joinedaxis` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `allieswon` smallint(5) unsigned NOT NULL default '0',
  `allieslost` smallint(5) unsigned NOT NULL default '0',
  `axiswon` smallint(5) unsigned NOT NULL default '0',
  `axislost` smallint(5) unsigned NOT NULL default '0',
  `bombplanted` smallint(5) unsigned NOT NULL default '0',
  `bombdefused` smallint(5) unsigned NOT NULL default '0',
  `killedbombplanter` smallint(5) unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `axisflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `flagscaptured` smallint(5) unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint(5) unsigned NOT NULL default '0',
  `axisflagsblocked` smallint(5) unsigned NOT NULL default '0',
  `flagsblocked` smallint(5) unsigned NOT NULL default '0',
  `alliesscore` smallint(5) unsigned NOT NULL default '0',
  `axisscore` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
