CREATE TABLE `ps_map_data_halflife_natural` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `alienkills` smallint(5) unsigned NOT NULL default '0',
  `marinekills` smallint(5) unsigned NOT NULL default '0',
  `joinedalien` smallint(5) unsigned NOT NULL default '0',
  `joinedmarine` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `alienwon` smallint(5) unsigned NOT NULL default '0',
  `marinewon` smallint(5) unsigned NOT NULL default '0',
  `alienlost` smallint(5) unsigned NOT NULL default '0',
  `marinelost` smallint(5) unsigned NOT NULL default '0',
  `structuresbuilt` smallint(5) unsigned NOT NULL default '0',
  `structuresdestroyed` smallint(5) unsigned NOT NULL default '0',
  `structuresrecycled` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_data_halflife_natural` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `alienkills` smallint(5) unsigned NOT NULL default '0',
  `marinekills` smallint(5) unsigned NOT NULL default '0',
  `aliendeaths` smallint(5) unsigned NOT NULL default '0',
  `marinedeaths` smallint(5) unsigned NOT NULL default '0',
  `joinedalien` smallint(5) unsigned NOT NULL default '0',
  `joinedmarine` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `alienwon` smallint(5) unsigned NOT NULL default '0',
  `marinewon` smallint(5) unsigned NOT NULL default '0',
  `alienlost` smallint(5) unsigned NOT NULL default '0',
  `marinelost` smallint(5) unsigned NOT NULL default '0',
  `votedown` smallint(5) unsigned NOT NULL default '0',
  `commander` smallint(5) unsigned NOT NULL,
  `commanderwon` smallint(5) unsigned NOT NULL default '0',
  `structuresbuilt` smallint(5) unsigned NOT NULL default '0',
  `structuresdestroyed` smallint(5) unsigned NOT NULL default '0',
  `structuresrecycled` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_maps_halflife_natural` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `alienkills` smallint(5) unsigned NOT NULL default '0',
  `marinekills` smallint(5) unsigned NOT NULL default '0',
  `aliendeaths` smallint(5) unsigned NOT NULL default '0',
  `marinedeaths` smallint(5) unsigned NOT NULL default '0',
  `joinedalien` smallint(5) unsigned NOT NULL default '0',
  `joinedmarine` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `alienwon` smallint(5) unsigned NOT NULL default '0',
  `marinewon` smallint(5) unsigned NOT NULL default '0',
  `alienlost` smallint(5) unsigned NOT NULL default '0',
  `marinelost` smallint(5) unsigned NOT NULL default '0',
  `votedown` smallint(5) unsigned NOT NULL default '0',
  `commander` smallint(5) unsigned NOT NULL,
  `commanderwon` smallint(5) unsigned NOT NULL default '0',
  `structuresbuilt` smallint(5) unsigned NOT NULL default '0',
  `structuresdestroyed` smallint(5) unsigned NOT NULL default '0',
  `structuresrecycled` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
