CREATE TABLE `ps_map_data_halflife_tf2` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `redkills` smallint(5) unsigned NOT NULL default '0',
  `redassists` smallint(5) unsigned NOT NULL default '0',
  `bluekills` smallint(5) unsigned NOT NULL default '0',
  `blueassists` smallint(5) unsigned NOT NULL default '0',
  `joinedred` smallint(5) unsigned NOT NULL default '0',
  `joinedblue` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `redwon` smallint(5) unsigned NOT NULL default '0',
  `redlost` smallint(5) unsigned NOT NULL default '0',
  `bluewon` smallint(5) unsigned NOT NULL default '0',
  `bluelost` smallint(5) unsigned NOT NULL default '0',
  `redflagsdefended` smallint(5) unsigned NOT NULL default '0',
  `blueflagsdefended` smallint(5) unsigned NOT NULL default '0',
  `redflagsdropped` smallint(5) unsigned NOT NULL default '0',
  `blueflagsdropped` smallint(5) unsigned NOT NULL default '0',
  `redflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `blueflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `redpointcaptured` smallint(5) unsigned NOT NULL default '0',
  `bluepointcaptured` smallint(5) unsigned NOT NULL default '0',
  `redcaptureblocked` smallint(5) unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint(5) unsigned NOT NULL default '0',
  `flagscaptured` smallint(5) unsigned NOT NULL default '0',
  `flagsdefended` smallint(5) unsigned NOT NULL default '0',
  `captureblocked` smallint(5) unsigned NOT NULL default '0',
  `pointcaptured` smallint(5) unsigned NOT NULL default '0',
  `redflagspickedup` smallint(5) unsigned NOT NULL default '0',
  `blueflagspickedup` smallint(5) unsigned NOT NULL default '0',
  `dispenserdestroy` smallint(5) unsigned NOT NULL default '0',
  `sentrydestroy` smallint(5) unsigned NOT NULL default '0',
  `teleporterdestroy` smallint(5) unsigned NOT NULL default '0',
  `sapperdestroy` smallint(5) unsigned NOT NULL default '0',
  `itemsdestroyed` smallint(5) unsigned NOT NULL default '0',
  `itemsbuilt` smallint(5) unsigned NOT NULL default '0',
  `dominations` smallint(5) unsigned NOT NULL default '0',
  `assists` smallint(5) unsigned NOT NULL default '0',
  `backstabkills` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_data_halflife_tf2` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `redkills` smallint(5) unsigned NOT NULL default '0',
  `redassists` smallint(5) unsigned NOT NULL default '0',
  `bluekills` smallint(5) unsigned NOT NULL default '0',
  `blueassists` smallint(5) unsigned NOT NULL default '0',
  `reddeaths` smallint(5) unsigned NOT NULL default '0',
  `bluedeaths` smallint(5) unsigned NOT NULL default '0',
  `joinedred` smallint(5) unsigned NOT NULL default '0',
  `joinedblue` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `redwon` smallint(5) unsigned NOT NULL default '0',
  `redlost` smallint(5) unsigned NOT NULL default '0',
  `bluewon` smallint(5) unsigned NOT NULL default '0',
  `bluelost` smallint(5) unsigned NOT NULL default '0',
  `redflagsdefended` smallint(5) unsigned NOT NULL default '0',
  `blueflagsdefended` smallint(5) unsigned NOT NULL default '0',
  `redflagsdropped` smallint(5) unsigned NOT NULL default '0',
  `blueflagsdropped` smallint(5) unsigned NOT NULL default '0',
  `redflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `blueflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `redpointcaptured` smallint(5) unsigned NOT NULL default '0',
  `bluepointcaptured` smallint(5) unsigned NOT NULL default '0',
  `redcaptureblocked` smallint(5) unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint(5) unsigned NOT NULL default '0',
  `redflagspickedup` smallint(5) unsigned NOT NULL default '0',
  `blueflagspickedup` smallint(5) unsigned NOT NULL default '0',
  `flagscaptured` smallint(5) unsigned NOT NULL default '0',
  `flagsdefended` smallint(5) unsigned NOT NULL default '0',
  `captureblocked` smallint(5) unsigned NOT NULL default '0',
  `pointcaptured` smallint(5) unsigned NOT NULL default '0',
  `dispenserdestroy` smallint(5) unsigned NOT NULL default '0',
  `sentrydestroy` smallint(5) unsigned NOT NULL default '0',
  `teleporterdestroy` smallint(5) unsigned NOT NULL default '0',
  `sapperdestroy` smallint(5) unsigned NOT NULL default '0',
  `itemsdestroyed` smallint(5) unsigned NOT NULL default '0',
  `itemsbuilt` smallint(5) unsigned NOT NULL default '0',
  `dominations` smallint(5) unsigned NOT NULL default '0',
  `assists` smallint(5) unsigned NOT NULL default '0',
  `backstabkills` smallint(5) unsigned NOT NULL default '0',
  `revenge` smallint(5) unsigned NOT NULL default '0',
  `chargedeployed` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_maps_halflife_tf2` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `redkills` smallint(5) unsigned NOT NULL default '0',
  `redassists` smallint(5) unsigned NOT NULL default '0',
  `bluekills` smallint(5) unsigned NOT NULL default '0',
  `blueassists` smallint(5) unsigned NOT NULL default '0',
  `reddeaths` smallint(5) unsigned NOT NULL default '0',
  `bluedeaths` smallint(5) unsigned NOT NULL default '0',
  `joinedred` smallint(5) unsigned NOT NULL default '0',
  `joinedblue` smallint(5) unsigned NOT NULL default '0',
  `joinedspectator` smallint(5) unsigned NOT NULL default '0',
  `redwon` smallint(5) unsigned NOT NULL default '0',
  `redlost` smallint(5) unsigned NOT NULL default '0',
  `bluewon` smallint(5) unsigned NOT NULL default '0',
  `bluelost` smallint(5) unsigned NOT NULL default '0',
  `redflagsdefended` smallint(5) unsigned NOT NULL default '0',
  `blueflagsdefended` smallint(5) unsigned NOT NULL default '0',
  `redflagsdropped` smallint(5) unsigned NOT NULL default '0',
  `blueflagsdropped` smallint(5) unsigned NOT NULL default '0',
  `redflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `blueflagscaptured` smallint(5) unsigned NOT NULL default '0',
  `redpointcaptured` smallint(5) unsigned NOT NULL default '0',
  `bluepointcaptured` smallint(5) unsigned NOT NULL default '0',
  `redcaptureblocked` smallint(5) unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint(5) unsigned NOT NULL default '0',
  `redflagspickedup` smallint(5) unsigned NOT NULL default '0',
  `blueflagspickedup` smallint(5) unsigned NOT NULL default '0',
  `flagscaptured` smallint(5) unsigned NOT NULL default '0',
  `flagsdefended` smallint(5) unsigned NOT NULL default '0',
  `captureblocked` smallint(5) unsigned NOT NULL default '0',
  `pointcaptured` smallint(5) unsigned NOT NULL default '0',
  `dispenserdestroy` smallint(5) unsigned NOT NULL default '0',
  `sentrydestroy` smallint(5) unsigned NOT NULL default '0',
  `teleporterdestroy` smallint(5) unsigned NOT NULL default '0',
  `sapperdestroy` smallint(5) unsigned NOT NULL default '0',
  `itemsdestroyed` smallint(5) unsigned NOT NULL default '0',
  `itemsbuilt` smallint(5) unsigned NOT NULL default '0',
  `dominations` smallint(5) unsigned NOT NULL default '0',
  `assists` smallint(5) unsigned NOT NULL default '0',
  `backstabkills` smallint(5) unsigned NOT NULL default '0',
  `revenge` smallint(5) unsigned NOT NULL default '0',
  `chargedeployed` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_plr_roles_halflife_tf2` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `assists` smallint(5) unsigned NOT NULL default '0',
  `dominations` smallint(5) unsigned NOT NULL default '0',
  `backstabkills` smallint(5) unsigned NOT NULL default '0',
  `itemsbuilt` smallint(5) unsigned NOT NULL default '0',
  `itemsdestroyed` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ps_role_data_halflife_tf2` (
  `dataid` int(10) unsigned NOT NULL default '0',
  `assists` smallint(5) unsigned NOT NULL default '0',
  `dominations` smallint(5) unsigned NOT NULL default '0',
  `backstabkills` smallint(5) unsigned NOT NULL default '0',
  `itemsbuilt` smallint(5) unsigned NOT NULL default '0',
  `itemsdestroyed` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
