CREATE TABLE `ps_map_data_halflife_cstrike` (
  `dataid` int unsigned NOT NULL default '0',
  `ctkills` smallint unsigned NOT NULL default '0',
  `terroristkills` smallint unsigned NOT NULL default '0',
  `joinedct` smallint unsigned NOT NULL default '0',
  `joinedterrorist` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `bombdefuseattempts` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `bombexploded` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombrunner` smallint unsigned NOT NULL default '0',
  `killedhostages` smallint unsigned NOT NULL default '0',
  `rescuedhostages` smallint unsigned NOT NULL default '0',
  `touchedhostages` smallint unsigned NOT NULL default '0',
  `vipescaped` smallint unsigned NOT NULL default '0',
  `vipkilled` smallint unsigned NOT NULL default '0',
  `ctwon` smallint unsigned NOT NULL default '0',
  `ctlost` smallint unsigned NOT NULL default '0',
  `terroristwon` smallint unsigned NOT NULL default '0',
  `terroristlost` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_halflife_cstrike` (
  `dataid` int unsigned NOT NULL default '0',
  `ctkills` smallint unsigned NOT NULL default '0',
  `terroristkills` smallint unsigned NOT NULL default '0',
  `ctdeaths` smallint unsigned NOT NULL default '0',
  `terroristdeaths` smallint unsigned NOT NULL default '0',
  `joinedct` smallint unsigned NOT NULL default '0',
  `joinedterrorist` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `bombdefuseattempts` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `bombexploded` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombspawned` smallint unsigned NOT NULL default '0',
  `bombrunner` smallint unsigned NOT NULL default '0',
  `killedhostages` smallint unsigned NOT NULL default '0',
  `rescuedhostages` smallint unsigned NOT NULL default '0',
  `touchedhostages` smallint unsigned NOT NULL default '0',
  `vip` smallint unsigned NOT NULL default '0',
  `vipescaped` smallint unsigned NOT NULL default '0',
  `vipkilled` smallint unsigned NOT NULL default '0',
  `ctwon` smallint unsigned NOT NULL default '0',
  `ctlost` smallint unsigned NOT NULL default '0',
  `terroristwon` smallint unsigned NOT NULL default '0',
  `terroristlost` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_halflife_cstrike` (
  `dataid` int unsigned NOT NULL default '0',
  `ctkills` smallint unsigned NOT NULL default '0',
  `terroristkills` smallint unsigned NOT NULL default '0',
  `ctdeaths` smallint unsigned NOT NULL default '0',
  `terroristdeaths` smallint unsigned NOT NULL default '0',
  `joinedct` smallint unsigned NOT NULL default '0',
  `joinedterrorist` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `bombdefuseattempts` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `bombexploded` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombspawned` smallint unsigned NOT NULL default '0',
  `bombrunner` smallint unsigned NOT NULL default '0',
  `killedhostages` smallint unsigned NOT NULL default '0',
  `rescuedhostages` smallint unsigned NOT NULL default '0',
  `touchedhostages` smallint unsigned NOT NULL default '0',
  `vip` smallint unsigned NOT NULL default '0',
  `vipescaped` smallint unsigned NOT NULL default '0',
  `vipkilled` smallint unsigned NOT NULL default '0',
  `ctwon` smallint unsigned NOT NULL default '0',
  `ctlost` smallint unsigned NOT NULL default '0',
  `terroristwon` smallint unsigned NOT NULL default '0',
  `terroristlost` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
