CREATE TABLE `ps_map_data_halflife_firearms` (
  `dataid` int unsigned NOT NULL default '0',
  `red_forcekills` smallint unsigned NOT NULL default '0',
  `blue_forcekills` smallint unsigned NOT NULL default '0',
  `joinedred_force` smallint unsigned NOT NULL default '0',
  `joinedblue_force` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `red_forcewon` smallint unsigned NOT NULL default '0',
  `blue_forcewon` smallint unsigned NOT NULL default '0',
  `red_forcelost` smallint unsigned NOT NULL default '0',
  `blue_forcelost` smallint unsigned NOT NULL default '0',
  `bandage` smallint unsigned NOT NULL default '0',
  `medevac` smallint unsigned NOT NULL default '0',
  `capturepoint` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ps_plr_data_halflife_firearms` (
  `dataid` int unsigned NOT NULL default '0',
  `red_forcekills` smallint unsigned NOT NULL default '0',
  `blue_forcekills` smallint unsigned NOT NULL default '0',
  `red_forcedeaths` smallint unsigned NOT NULL default '0',
  `blue_forcedeaths` smallint unsigned NOT NULL default '0',
  `joinedred_force` smallint unsigned NOT NULL default '0',
  `joinedblue_force` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `red_forcewon` smallint unsigned NOT NULL default '0',
  `blue_forcewon` smallint unsigned NOT NULL default '0',
  `red_forcelost` smallint unsigned NOT NULL default '0',
  `blue_forcelost` smallint unsigned NOT NULL default '0',
  `bandage` smallint unsigned NOT NULL default '0',
  `medevac` smallint unsigned NOT NULL default '0',
  `capturepoint` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ps_plr_maps_halflife_firearms` (
  `dataid` int unsigned NOT NULL default '0',
  `red_forcekills` smallint unsigned NOT NULL default '0',
  `blue_forcekills` smallint unsigned NOT NULL default '0',
  `red_forcedeaths` smallint unsigned NOT NULL default '0',
  `blue_forcedeaths` smallint unsigned NOT NULL default '0',
  `joinedred_force` smallint unsigned NOT NULL default '0',
  `joinedblue_force` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `red_forcewon` smallint unsigned NOT NULL default '0',
  `blue_forcewon` smallint unsigned NOT NULL default '0',
  `red_forcelost` smallint unsigned NOT NULL default '0',
  `blue_forcelost` smallint unsigned NOT NULL default '0',
  `bandage` smallint unsigned NOT NULL default '0',
  `medevac` smallint unsigned NOT NULL default '0',
  `capturepoint` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
