CREATE TABLE `ps_map_data_halflife_natural` (
  `dataid` int unsigned NOT NULL default '0',
  `alienkills` smallint unsigned NOT NULL default '0',
  `marinekills` smallint unsigned NOT NULL default '0',
  `joinedalien` smallint unsigned NOT NULL default '0',
  `joinedmarine` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `alienwon` smallint unsigned NOT NULL default '0',
  `marinewon` smallint unsigned NOT NULL default '0',
  `alienlost` smallint unsigned NOT NULL default '0',
  `marinelost` smallint unsigned NOT NULL default '0',
  `structuresbuilt` smallint unsigned NOT NULL default '0',
  `structuresdestroyed` smallint unsigned NOT NULL default '0',
  `structuresrecycled` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_halflife_natural` (
  `dataid` int unsigned NOT NULL default '0',
  `alienkills` smallint unsigned NOT NULL default '0',
  `marinekills` smallint unsigned NOT NULL default '0',
  `aliendeaths` smallint unsigned NOT NULL default '0',
  `marinedeaths` smallint unsigned NOT NULL default '0',
  `joinedalien` smallint unsigned NOT NULL default '0',
  `joinedmarine` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `alienwon` smallint unsigned NOT NULL default '0',
  `marinewon` smallint unsigned NOT NULL default '0',
  `alienlost` smallint unsigned NOT NULL default '0',
  `marinelost` smallint unsigned NOT NULL default '0',
  `votedown` smallint unsigned NOT NULL default '0',
  `commander` smallint unsigned NOT NULL,
  `commanderwon` smallint unsigned NOT NULL default '0',
  `structuresbuilt` smallint unsigned NOT NULL default '0',
  `structuresdestroyed` smallint unsigned NOT NULL default '0',
  `structuresrecycled` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_halflife_natural` (
  `dataid` int unsigned NOT NULL default '0',
  `alienkills` smallint unsigned NOT NULL default '0',
  `marinekills` smallint unsigned NOT NULL default '0',
  `aliendeaths` smallint unsigned NOT NULL default '0',
  `marinedeaths` smallint unsigned NOT NULL default '0',
  `joinedalien` smallint unsigned NOT NULL default '0',
  `joinedmarine` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `alienwon` smallint unsigned NOT NULL default '0',
  `marinewon` smallint unsigned NOT NULL default '0',
  `alienlost` smallint unsigned NOT NULL default '0',
  `marinelost` smallint unsigned NOT NULL default '0',
  `votedown` smallint unsigned NOT NULL default '0',
  `commander` smallint unsigned NOT NULL,
  `commanderwon` smallint unsigned NOT NULL default '0',
  `structuresbuilt` smallint unsigned NOT NULL default '0',
  `structuresdestroyed` smallint unsigned NOT NULL default '0',
  `structuresrecycled` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
