CREATE TABLE `ps_map_data_halflife_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `redkills` smallint unsigned NOT NULL default '0',
  `redassists` smallint unsigned NOT NULL default '0',
  `bluekills` smallint unsigned NOT NULL default '0',
  `blueassists` smallint unsigned NOT NULL default '0',
  `joinedred` smallint unsigned NOT NULL default '0',
  `joinedblue` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `redwon` smallint unsigned NOT NULL default '0',
  `redlost` smallint unsigned NOT NULL default '0',
  `bluewon` smallint unsigned NOT NULL default '0',
  `bluelost` smallint unsigned NOT NULL default '0',
  `redflagsdefended` smallint unsigned NOT NULL default '0',
  `blueflagsdefended` smallint unsigned NOT NULL default '0',
  `redflagsdropped` smallint unsigned NOT NULL default '0',
  `blueflagsdropped` smallint unsigned NOT NULL default '0',
  `redflagscaptured` smallint unsigned NOT NULL default '0',
  `blueflagscaptured` smallint unsigned NOT NULL default '0',
  `redpointcaptured` smallint unsigned NOT NULL default '0',
  `bluepointcaptured` smallint unsigned NOT NULL default '0',
  `redcaptureblocked` smallint unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `captureblocked` smallint unsigned NOT NULL default '0',
  `pointcaptured` smallint unsigned NOT NULL default '0',
  `redflagspickedup` smallint unsigned NOT NULL default '0',
  `blueflagspickedup` smallint unsigned NOT NULL default '0',
  `dispenserdestroy` smallint unsigned NOT NULL default '0',
  `sentrydestroy` smallint unsigned NOT NULL default '0',
  `teleporterdestroy` smallint unsigned NOT NULL default '0',
  `sapperdestroy` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ps_plr_data_halflife_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `redkills` smallint unsigned NOT NULL default '0',
  `redassists` smallint unsigned NOT NULL default '0',
  `bluekills` smallint unsigned NOT NULL default '0',
  `blueassists` smallint unsigned NOT NULL default '0',
  `reddeaths` smallint unsigned NOT NULL default '0',
  `bluedeaths` smallint unsigned NOT NULL default '0',
  `joinedred` smallint unsigned NOT NULL default '0',
  `joinedblue` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `redwon` smallint unsigned NOT NULL default '0',
  `redlost` smallint unsigned NOT NULL default '0',
  `bluewon` smallint unsigned NOT NULL default '0',
  `bluelost` smallint unsigned NOT NULL default '0',
  `redflagsdefended` smallint unsigned NOT NULL default '0',
  `blueflagsdefended` smallint unsigned NOT NULL default '0',
  `redflagsdropped` smallint unsigned NOT NULL default '0',
  `blueflagsdropped` smallint unsigned NOT NULL default '0',
  `redflagscaptured` smallint unsigned NOT NULL default '0',
  `blueflagscaptured` smallint unsigned NOT NULL default '0',
  `redpointcaptured` smallint unsigned NOT NULL default '0',
  `bluepointcaptured` smallint unsigned NOT NULL default '0',
  `redcaptureblocked` smallint unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint unsigned NOT NULL default '0',
  `redflagspickedup` smallint unsigned NOT NULL default '0',
  `blueflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `captureblocked` smallint unsigned NOT NULL default '0',
  `pointcaptured` smallint unsigned NOT NULL default '0',
  `dispenserdestroy` smallint unsigned NOT NULL default '0',
  `sentrydestroy` smallint unsigned NOT NULL default '0',
  `teleporterdestroy` smallint unsigned NOT NULL default '0',
  `sapperdestroy` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `revenge` smallint unsigned NOT NULL default '0',
  `chargedeployed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ps_plr_maps_halflife_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `redkills` smallint unsigned NOT NULL default '0',
  `redassists` smallint unsigned NOT NULL default '0',
  `bluekills` smallint unsigned NOT NULL default '0',
  `blueassists` smallint unsigned NOT NULL default '0',
  `reddeaths` smallint unsigned NOT NULL default '0',
  `bluedeaths` smallint unsigned NOT NULL default '0',
  `joinedred` smallint unsigned NOT NULL default '0',
  `joinedblue` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `redwon` smallint unsigned NOT NULL default '0',
  `redlost` smallint unsigned NOT NULL default '0',
  `bluewon` smallint unsigned NOT NULL default '0',
  `bluelost` smallint unsigned NOT NULL default '0',
  `redflagsdefended` smallint unsigned NOT NULL default '0',
  `blueflagsdefended` smallint unsigned NOT NULL default '0',
  `redflagsdropped` smallint unsigned NOT NULL default '0',
  `blueflagsdropped` smallint unsigned NOT NULL default '0',
  `redflagscaptured` smallint unsigned NOT NULL default '0',
  `blueflagscaptured` smallint unsigned NOT NULL default '0',
  `redpointcaptured` smallint unsigned NOT NULL default '0',
  `bluepointcaptured` smallint unsigned NOT NULL default '0',
  `redcaptureblocked` smallint unsigned NOT NULL default '0',
  `bluecaptureblocked` smallint unsigned NOT NULL default '0',
  `redflagspickedup` smallint unsigned NOT NULL default '0',
  `blueflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `captureblocked` smallint unsigned NOT NULL default '0',
  `pointcaptured` smallint unsigned NOT NULL default '0',
  `dispenserdestroy` smallint unsigned NOT NULL default '0',
  `sentrydestroy` smallint unsigned NOT NULL default '0',
  `teleporterdestroy` smallint unsigned NOT NULL default '0',
  `sapperdestroy` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `revenge` smallint unsigned NOT NULL default '0',
  `chargedeployed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ps_plr_roles_halflife_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ps_role_data_halflife_tf2` (
  `dataid` int unsigned NOT NULL default '0',
  `assists` smallint unsigned NOT NULL default '0',
  `dominations` smallint unsigned NOT NULL default '0',
  `backstabkills` smallint unsigned NOT NULL default '0',
  `itemsbuilt` smallint unsigned NOT NULL default '0',
  `itemsdestroyed` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
