CREATE TABLE `ps_map_data_soldat` (
  `dataid` int unsigned NOT NULL default '0',
  `alphakills` smallint unsigned NOT NULL default '0',
  `bravokills` smallint unsigned NOT NULL default '0',
  `alphawon` smallint unsigned NOT NULL default '0',
  `alphalost` smallint unsigned NOT NULL default '0',
  `bravowon` smallint unsigned NOT NULL default '0',
  `bravolost` smallint unsigned NOT NULL default '0',
  `alphaflagscaptured` smallint unsigned NOT NULL default '0',
  `bravoflagscaptured` smallint unsigned NOT NULL default '0',
  `alphaflagsdefended` smallint unsigned NOT NULL default '0',
  `bravoflagsdefended` smallint unsigned NOT NULL default '0',
  `alphaflagspickedup` smallint unsigned NOT NULL default '0',
  `bravoflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `joinedalpha` smallint unsigned NOT NULL default '0',
  `joinedbravo` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ps_plr_data_soldat` (
  `dataid` int unsigned NOT NULL default '0',
  `alphakills` smallint unsigned NOT NULL default '0',
  `bravokills` smallint unsigned NOT NULL default '0',
  `alphadeaths` smallint unsigned NOT NULL default '0',
  `bravodeaths` smallint unsigned NOT NULL default '0',
  `alphawon` smallint unsigned NOT NULL default '0',
  `alphalost` smallint unsigned NOT NULL default '0',
  `bravowon` smallint unsigned NOT NULL default '0',
  `bravolost` smallint unsigned NOT NULL default '0',
  `alphaflagscaptured` smallint unsigned NOT NULL default '0',
  `bravoflagscaptured` smallint unsigned NOT NULL default '0',
  `alphaflagsdefended` smallint unsigned NOT NULL default '0',
  `bravoflagsdefended` smallint unsigned NOT NULL default '0',
  `alphaflagspickedup` smallint unsigned NOT NULL default '0',
  `bravoflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `joinedalpha` smallint unsigned NOT NULL default '0',
  `joinedbravo` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
CREATE TABLE `ps_plr_maps_soldat` (
  `dataid` int unsigned NOT NULL default '0',
  `alphakills` smallint unsigned NOT NULL default '0',
  `bravokills` smallint unsigned NOT NULL default '0',
  `alphadeaths` smallint unsigned NOT NULL default '0',
  `bravodeaths` smallint unsigned NOT NULL default '0',
  `alphawon` smallint unsigned NOT NULL default '0',
  `alphalost` smallint unsigned NOT NULL default '0',
  `bravowon` smallint unsigned NOT NULL default '0',
  `bravolost` smallint unsigned NOT NULL default '0',
  `alphaflagscaptured` smallint unsigned NOT NULL default '0',
  `bravoflagscaptured` smallint unsigned NOT NULL default '0',
  `alphaflagsdefended` smallint unsigned NOT NULL default '0',
  `bravoflagsdefended` smallint unsigned NOT NULL default '0',
  `alphaflagspickedup` smallint unsigned NOT NULL default '0',
  `bravoflagspickedup` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `flagsdefended` smallint unsigned NOT NULL default '0',
  `joinedalpha` smallint unsigned NOT NULL default '0',
  `joinedbravo` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
